bible_book_mapping = {
    'Gn': 'Genesis',
    'Ex': 'Exodus',
    'Lv': 'Leviticus',
    'Nu': 'Numbers',
    'Dt': 'Deuteronomy',
    'Jsh': 'Joshua',
    'Jdg': 'Judges',
    'Ruth': 'Ruth',
    '1Sa': '1 Samuel',
    '2Sa': '2 Samuel',
    '1Ki': '1 Kings',
    '2Ki': '2 Kings',
    '1Ch': '1 Chronicles',
    '2Ch': '2 Chronicles',
    'Ezr': 'Ezra',
    'Neh': 'Nehemiah',
    'Esth': 'Esther',
    'Job': 'Job',
    'Ps': 'Psalms',
    'Pr': 'Proverbs',
    'Eccl': 'Ecclesiastes',
    'Song': 'Song of Solomon',
    'Is': 'Isaiah',
    'Jer': 'Jeremiah',
    'La': 'Lamentations',
    'Eze': 'Ezekiel',
    'Dn': 'Daniel',
    'Ho': 'Hosea',
    'Joel': 'Joel',
    'Am': 'Amos',
    'Ob': 'Obadiah',
    'Jon': 'Jonah',
    'Mic': 'Micah',
    'Nah': 'Nahum',
    'Hab': 'Habakkuk',
    'Zph': 'Zephaniah',
    'Hag': 'Haggai',
    'Zech': 'Zechariah',
    'Mal': 'Malachi',
    'Mt': 'Matthew',
    'Mk': 'Mark',
    'Lk': 'Luke',
    'Jn': 'John',
    'Act': 'Acts',
    'Ro': 'Romans',
    '1Co': '1 Corinthians',
    '2Co': '2 Corinthians',
    'Gal': 'Galatians',
    'Eph': 'Ephesians',
    'Phil': 'Philippians',
    'Col': 'Colossians',
    '1Th': '1 Thessalonians',
    '2Th': '2 Thessalonians',
    '1Ti': '1 Timothy',
    '2Ti': '2 Timothy',
    'Tit': 'Titus',
    'Philemon': 'Philemon',
    'He': 'Hebrews',
    'Jas': 'James',
    '1Pe': '1 Peter',
    '2Pe': '2 Peter',
    '1 Jn': '1 John',
    '2Jn': '2 John',
    '3 Jn': '3 John',
    'Jude': 'Jude',
    'Rev': 'Revelation'
}
